### PR TITLE
Initial work towards HEIC to JPG conversion

### PR DESCRIPTION
**Pull request by chrisayoub**
This pull request relates to issue:
https://github.com/ndbroadbent/icloud_photos_downloader/issues/108

I have included code changes that use ImageMagick to convert downloaded HEIC images to JPG images. I have also updated the README to account for the new command line option.

Additionally, the README includes instructions on how to install ImageMagick on various platforms with HEIC support. So far, I have verified these steps on Ubuntu and Windows 10, and the Mac steps seem correct, but I am unable to formally verify this.

I could not figure out how to create a test case for this. Looking at the existing test cases, I am sure this is possible, but the VCR cassette tests were too complicated for me to manually modify to include an HEIC file (so conversion can be tested). Help would be appreciated with creating a test case for this.

Additionally, in running the existing test cases on my system (Ubuntu, with timezone GMT -6), I found that two of the test cases fail due to my system's timezone offset. I have included fixes for these specific testcases.

### CODE REVIEW

**Comment by sthenge** [comment]
for what its's worth, I made the changes suggested by chrisayoub on my file server and it seems to work okay.  I'm not a python tester by any definition so I have no idea if everything works correctly, however, all  .heic images were converted to jpg as advertised, so I'm happy.

**Comment by deferred** [comment]
Will this Pull Request be merged at some point?

**Comment by ndbroadbent** [comment]
@deferred not yet unfortunately, I need a few more test cases to bring the test coverage up to 100%. (Sorry I don’t have time to add these myself.)

**Comment by menkej** [comment]
I could offer to add test cases for this, even though my phone seems to old to use HEIC... ;-) I just need a hint how I can add to this pull request. Still getting used to the GitHub workflow...

**Comment by sthenge** [comment]
As an after thought to my previous comment, I implemented this on Linux Mint 19.1 using python 3.6.

If there is a template for testing that I can review, I might be able to provide further testing.  Let me know.

**Comment by menkej** [comment]
> If there is a template for testing that I can review, I might be able to provide further testing. Let me know.

Just have a look at the existing test cases. You can copy one of them as a new test case for HEIC download. I recomend to add a new cassette with your iCloud response. Don't forget to removed your name/mail from the cassette before checkin.

**Comment by ndbroadbent** [comment]
Hello, I'm just going through the old PRs on this project again, and I'll leave this open for now since it would be a great feature! If anyone wants to jump in, rebase and fix conflicts, and add some test cases to show that HEIC conversion is working, then I'd be happy to merge!

Also I just merged another PR that adds a Dockerfile to the root directory, so this will need to be updated.

**Comment by Vlad1mir-D** [comment]
Maybe I'll do it...

**Pull request closed without merging**
