### PR TITLE
Fix so that the logger only returns one global logger, allowing logging

### PR DESCRIPTION
**Pull request by koldinger**
settings to be used globally, and eliminating the overlogging when a log-level is specified.

### CODE REVIEW

**Comment by MrBenFTW** [comment]
How did you get it working? I have an issue with albums, #150

**Comment by koldinger** [comment]
Can't imagine that this is related.   This merely uses a common logging object, so that the settings get reflected everywhere, rather than a separate logging object for each component.

**Comment by MrBenFTW** [comment]
I understand, just asking how you got your build to work, since the master is broken

**Comment by koldinger** [comment]
I just ran it.   Seems to be fine.

**Comment by ndbroadbent** [comment]
Hi @koldinger, thanks very much for the PR, and sorry for the delay! I was just wondering if you could please take a look at the pylint errors in the Travis CI build? (If you are still interested)

```
3.73s$ pylint icloudpd
************* Module icloudpd.logger
icloudpd/logger.py:35:0: C0103: Constant name "logger" doesn't conform to UPPER_CASE naming style (invalid-name)
icloudpd/logger.py:38:4: C0103: Constant name "logger" doesn't conform to UPPER_CASE naming style (invalid-name)
icloudpd/logger.py:38:4: W0603: Using the global statement (global-statement)
icloudpd/logger.py:39:4: R1705: Unnecessary "else" after "return" (no-else-return)
```

**Comment by menkej** [comment]
I like using a singleton for logging, so I understand the intention. Anyways pylint has a good point not to use globals, etc. But to solve this we should restructure the program in a more object-oriented way (to be a class), so that we could just put the logger into an instance variable. But this is quite a big change...

**Comment by menkej** [comment]
Thanks again for your pull request. We added a different solution with #194

**Pull request closed without merging**
