### PR TITLE
Empty folders

### LINKED ISSUE #185: Empty directory structure being created
If I run the following command:
```
/usr/bin/icloudpd --directory /test --cookie-directory /cookie --username fake@email.com --folder-structure {:%Y} --only-print-filenames
```
the script will create an empty directory structure under the download directory. Is this expected behaviour?

The name "only-print-filenames" suggest that no changes should be made to the filesystem, only a list of files should be displayed.

### PR DESCRIPTION
**Pull request by menkej**
fixes #185 

and a little realpath-issue for the scripts I'm using on Mac....

### CODE REVIEW

**Comment by AndreyNikiforov** [comment]
@menkej add test for the bug in question, please.

**Review by AndreyNikiforov — APPROVED** [review]

**Comment by AndreyNikiforov** [comment]
@menkej do you mind adding your fix to CHANGELOG (separate PR) so it will be easier to build release notes? I am sorry, I missed that during review

**Comment by menkej** [comment]
> @menkej do you mind adding your fix to CHANGELOG

Sure. CHANGELOG is now, so I missed that, too. I'd like fix the mess (or not mess) I created with folder-structure=none first and then cleanup CHANGELOG. What do you think?

**Comment by AndreyNikiforov** [comment]
> > @menkej do you mind adding your fix to CHANGELOG
> 
> Sure. CHANGELOG is now, so I missed that, too. I'd like fix the mess (or not mess) I created with folder-structure=none first and then cleanup CHANGELOG. What do you think?

This change is in master (==affecting anybody working with master) and can go to new release at any time. Other change is not completed/merged yet (==isolated), so it can hold its broken state without affecting others. Adding one line to change log is quick as well, so I recommend adding changelog for your feature first and then dive into rebase challenge.

**Pull request merged**
