### PR TITLE
Add AUR link to README

### PR DESCRIPTION
**Pull request by undefined-landmark**
Hi,

Thanks for the nice tool! Since a package was not available on the AUR yet I created a simple PKGBUILD that sets up the icloudpd binary. This should make using and updating the tool a bit easier for Arch users. Because this provides another way to install the package I added this option to the README. If there is any additional documentation you'd like me to write I'd be happy to do so, just let me know.

### CODE REVIEW

**Comment by AndreyNikiforov** [comment]
The idea to support native package support for linux is great! 

For Arch linux it is pacman, so end result of supporting pacman should be that end user should be able to install icloudpd using, say, `pacman -S icloudpd`. Are we getting that user experience by adding AUR? (I not familiar with Arch/pacman/AUR).

What are the capabilities for permission control in pacman registry? For supported registries/repositories/etc we try to keep accounts of individual members/admins organized into org/group, so that access is not locked to one individual.

**Comment by undefined-landmark** [comment]
AUR packages are first compiled, manually or by an [AUR helper](https://wiki.archlinux.org/title/AUR_helpers), and then installed through pacman. A basic description of AUR is best found on the wiki [wiki](https://wiki.archlinux.org/title/Arch_User_Repository). Via the yay AUR helper an install would only be a simple `yay -S icloudpd-bin`.

AUR allows for co-maintainers. So I could add additional people if available. If for some reason I would stop maintaining the package suddenly the package can be flagged though an 'Orphan Request'. If I don't respond someone else will be able to take over maintenance. Exact details can be found on the [wiki](https://wiki.archlinux.org/title/AUR_submission_guidelines#Requests) again :)

**Comment by AndreyNikiforov** [comment]
I looked at the [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=icloudpd-bin) -- it is good that you are using existing released binaries instead recompiling. How can AUR/PKGBUILD support multiple architectures? icloudpd and archlinux both support amd64, arm32, and arm64 IIUC.

**Comment by undefined-landmark** [comment]
There are builtin PKGBUILD options to allow for installation on different architectures. Basically comes down to adding extra sources and checksums for each architecture. I can take a look and update the PKGBUILD accordingly.

**Comment by AndreyNikiforov** [comment]
> There are builtin PKGBUILD options to allow for installation on different architectures. Basically comes down to adding extra sources and checksums for each architecture. I can take a look and update the PKGBUILD accordingly.

Awesome! May I also suggest renaming package to `icloudpd` (remove `-bin`). To end user it is irrelevant information -- they just install icloudpd and the fact that it uses precompiled binaries instead of building from the source should/can be hidden.

**Comment by undefined-landmark** [comment]
The bin suffix is an AUR submission rule. It indicates that the package uses prebuilt binaries. No suffix would indicate the package is built from source. So with the current PKGBUILD I can't just remove it unfortunately.

Making a PKGBUILD that builds from source is possible of course. Albeit a bit more effort.

Reference: 
[AUR guidelines](https://wiki.archlinux.org/title/AUR_submission_guidelines)
> Packages that use prebuilt deliverables, when the sources are available, must use the -bin suffix. An exception to this is with Java. The AUR should not contain the binary tarball created by makepkg, nor should it contain the filelist.

**Comment by undefined-landmark** [comment]
The [PKGBUILD](https://aur.archlinux.org/packages/icloudpd-bin) now supports armv7h, arm64 and i686. I don't have those architectures around to test but, assuming I matched the architectures and bins correctly, they should function.

**Comment by undefined-landmark** [comment]
Thanks for the quick merge. Just saw there's another set of download links at the start of the README. Bit inattentive on my part. Something I noticed before is that the links point to README's of each download option, instead of direct links. Is there any need for such a README for the AUR option?

Can fix both of course. But already great that a direct link is visible in the README now.

**Pull request merged**
