### PR TITLE
Delete photo/video after download successful

### PR DESCRIPTION
**Pull request by MatrixDai**
Added a new command line option `--delete-after-download` to allow user delete the photo right after download complete. The deleted items will moved to "Recent Deleted" system album.

The implementation reference from [this gist](https://gist.github.com/Tatsh/0b5a10a2d25f6c8466290401d2026055).

Related discussions:
#368 #314 #124 #332

### CODE REVIEW

**Comment by newone757** [comment]
I downloaded all of my photos using the normal docker template in unraid, then I saw your changes and ran them locally on my windows machine, pointed at the same share as my unraid install -- it's working great! Finally, I can free up space in our shared iCloud account! Thanks

**Comment by seiry-apt** [comment]
cool！+1

**Review by Nasipuk — APPROVED** [review]

**Comment by FinalTheory** [comment]
can we merge this change please?

**Comment by pawsie** [comment]
+1 Much needed feature. Can it be merged please?

**Comment by olegcarguy** [comment]
+1 Yes, can this feature be merged please?  @Nasipuk

**Comment by AndreyNikiforov** [comment]
@MatrixDai do you mind rebasing your diff, please? Thanks for providing tests for new functionality.

**Comment by MatrixDai** [comment]
> @MatrixDai do you mind rebasing your diff, please? Thanks for providing tests for new functionality.

@AndreyNikiforov Rebased with the master branch.

**Comment by AndreyNikiforov** [comment]
> > @MatrixDai do you mind rebasing your diff, please? Thanks for providing tests for new functionality.
> 
> @AndreyNikiforov Rebased with the master branch.

Quality checks are failing ;-( Please fix those.

You can run these checks locally (scripts/lint & script/test after installing all dependencies of course)

**Comment by MatrixDai** [comment]
Now, fixed lint and tests. @AndreyNikiforov 
Sorry didn't check locally, as I have upgrade local python to 3.11, it seems like the local develop env require python 3.9 on macOS M1.

**Comment by AndreyNikiforov** [comment]
> Now, fixed lint and tests. @AndreyNikiforov Sorry didn't check locally, as I have upgrade local python to 3.11, it seems like the local develop env require python 3.9 on macOS M1.

Yes, due to stale dependencies we have 3.9 as max supported version of Python now. You can run .devcontainer with 3.9 either locally or in Github Codespaces. Although containers are running Linux, Quality checks Github actions run on MacOs and Windows as well.

**Pull request merged**
