### PR TITLE
Handle OverflowError when downloading photos with invalid dates

### PR DESCRIPTION
**Pull request by ian-mcdowell**
Addresses issue #243

### CODE REVIEW

**Comment by menkej** [comment]
Could you possibly add a test case for this situation? I don't have such an image in my iCloud so I can't reproduce it...

**Comment by IMcD23** [comment]
I'm not familiar with your test code, and am not able to make more substantial changes here. 😞

**Comment by menkej** [comment]
> I'm not familiar with your test code, and am not able to make more substantial changes here. 😞

Ok, I understand. For testing we use recorded (and anonymised communication with iCloud. If you'd be able to re-run a download (as small as possible using --recent xyz for example) we could use this as a basis for a unit test:

1. I could write a test case
1. you re-run it with your credentials, communication is recorded
1. you remove your personal data (email-address mostly) from the rest response and provide that recording
1. we could use that recording to retest this specific change and make sure this does not happen again if we do a refactoring or update third party libs.

What do you think? If you want to have a look: a similar test case would be in `tests/test_download_photos.py` in p.e. method `test_download_photos_and_set_exif_exceptions`. A sample of the recorded data we use can be found in `tests/vcr_cassettes/listing_photos.yml`

**Comment by sensei-ishikawa** [comment]
this change did not work for me. i debbuged with pyCharm and time.mktime crashes when the year is 13. not sure why it is not assuming it is 2013.

i "hammered" the code and added a test for the year, if it falls outside of epoch, i just set it as the current date. totally not elegant, but functional.

def set_utime(download_path, created_date):
    """Set date & time of the file"""
    if created_date.year <= 1969:
        created_date = time.localtime()
    ctime = time.mktime(created_date.timetuple())
    os.utime(download_path, (ctime, ctime))


thanks folks for building this tool. it is great not to depend on the Photos app, which after the last 2 or 3 updates became a complete garbage. i have 100,000+ pictures and videos, Photos is unusable.

**Comment by menkej** [comment]
> this change did not work for me. i debbuged with pyCharm and time.mktime crashes when the year is 13. not sure why it is not assuming it is 2013.

Thanks for you patch! Are you able to provide a test-case for this situation, including a cassette that can be used to reproduce this behaviour?

**Comment by sensei-ishikawa** [comment]
actually, that crashed too with created_date.timetuple(), so i hard coded the date as epoch and i made the code even more awful. i am downloading 100,000+ items currently at 38%. 

how do i generate the cassete? i can reproduce the date object that causes the crash (tm_year = 13) and work on a better code to transform date into epoch. why aren't you using datetime? i don't recall ever using time.

def set_utime(download_path, created_date):
    """Set date & time of the file"""
    if created_date.year <= 1969:
        ctime = 1609396107
    else:
        ctime = time.mktime(created_date.timetuple())
    os.utime(download_path, (ctime, ctime))

**Comment by sensei-ishikawa** [comment]
the ugly code worked. 
119195it [41:09:14,  1.24s/it] 2021-01-02 05:50:31 INFO     All photos have been downloaded!

i read the docs for time() and re-wrote the code accordingly. i am running it again. if you give me some pointers, i can write the cassette for functional testing. i renamed the variable ctime as epoch for clarity.

def set_utime(download_path, created_date):
    """Set date & time of the file"""
    try:
        epoch = time.mktime(created_date.timetuple())
    except OverflowError or ValueError:
        epoch = time.time()
    os.utime(download_path, (epoch, epoch))

**Comment by AndreyNikiforov** [comment]
Folks, if we are dealing with datetimes without epoch, would it be reasonable to set epoch for these cases instead of catching overflow exception?

Here is a snipped from my unpublished code to explain the idea:

```
def datetime_cleansed(timestamp_ms: int) -> datetime.datetime:
    """
        Takes asset date as timestamp in ms and fallsback to 0
    """
    date_time = datetime.datetime.fromtimestamp(timestamp_ms / 1000, tz=datetime.timezone.utc)
    if date_time.year == datetime.MINYEAR and date_time.month == 1 and date_time.day == 1:
        # timestamp was built from time only
        return date_time.replace(year=1970)
    if date_time.year < 100:
        # missing epoch
        if date_time.year >= 70:
            return date_time.replace(year=1900+date_time.year)
        return date_time.replace(year=2000+date_time.year)
    return date_time
```

**Pull request closed without merging**
